[BUGFIX] Fix firewall configuration option value
It should be "reject" instead of "rejected". With "rejected" puppet says:
  Error: Failed to apply catalog: Parameter action failed on Firewall[080 Deny everybody else https]: Invalid value "rejected". Valid values are accept, reject, drop.  at /home/puppet-git/env/201501_master/modules/base/manifests/firewall/rule.pp:22